### ISSUE TITLE
Nice to have: Create alternative formulations using ChatGPT (chat.openai.com) from Open AI

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/content-development#108]

**Comment by KristellP** [comment]
@nelealbers: Let Kristell and Milon know when WP is done with this.

**Comment by Milonvv** [comment]
Alleen nog alternative formulations voor:

- [ ] HRS & (re)lapse dialog
- [ ] Deel Weekly reflection dialog
- [ ] Notifications
