### ISSUE TITLE
Overleggen met technisch team wat het makkelijkst is om roken te tracken 

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#111]
- In het bijzonder tijdens implementatie fase
- Willen wij ze dan elke keer laten reflecteren op de situaties waarin zij roken?
- Zoja, automatisc HRS gesprek opstarten na sigaret via tracker? Of liever via chat tracken?

**Comment by Milonvv** [comment]
- Leg uit waarom gedrag bijhouden belangrijk is, hoe ze hun sigaretten bij kunnen houden, ook letten op welke momenten dat zijn etc., tracken via NiceDay app als ze willen tracken in de app
- Ook voor PA - smartwatch
