### ISSUE TITLE
Think about what to do when user does not complete an activity

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#16]
- [x] Let's think about what to do when users do not complete activities, do we remind them to do it at another time? How? How often? When? This is especially important when two activities are dependent on each other.  
- [x] Will there be an overview of completed activities somewhere in the PF app (can be used by the VC to motivate to complete an activity, to show progress to the user and for the user to track own progress)? Answer: we will send users a notification at the beginning of each week to congratulate on starting a new week. This will be the progress tracking, we won't show users their progress in a different way.

**Comment by bscheltinga** [comment]
It's also an option to keep a timer and if the conversation is not continued for e.g. 20 minutes, a generic dialog will start. This dialog can start with the coach asking: "Hey, are you still there to finish the activity?" or "Do you want to continue this activity?

**Comment by Milonvv** [comment]
Let's think about what to do when users do not complete activities, do we remind them to do it at another time? How? How often? When? This is especially important when two activities are dependent on each other. -->
- Dialoog progress wordt opgeslagen aan de hand van checkpoints - herstart bij laatste checkpoint. Technical team gaat nadenken over goede momenten voor checkpoints (technisch gezien). Content team heeft aangegeven dat het het fijnst is als de checkpoints zijn nadat iemand grote antwoorden getypt / gegeven heeft.
- Na een uur komt er een reminder om de dialoog af te maken als een user inactief is en dan komen ze gewoon weer terug bij het laatste dialoog. 
- Als dit niet werkt en user pakt het dialoog niet weer op: 1) dan wordt user a non-user (vooral in preparation phase) of 2) komt user in free mode en zal het volgende gesprek gewoon weer gestart worden zoals bepaald of kan de user zelf commands typen
- Er moet dus een notificatie geschreven worden om users te reminden om een dialoog af te maken -->  toegevoegd aan lijstje van notificaties
