### ISSUE TITLE
Expert Meeting with Anke

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/content-development#17]
Discuss:
- [x] Generic rescheduling dialog (PPT)
- [ ] HRS reflection dialog
- [ ] 'Current self' part of future self dialog
- [x] Discuss #4 

Optional:
- [x] Discuss #16

**Comment by KristellP** [comment]
Minutes from the meeting with Anke: 

- Different wording for "Ik *gok* dat deze activiteit je gaat helpen met je doelen"
- There are no buttons in Nice Day. When giving the user an option to reply, say they have to type the chosen option(s). 
- Think about a way to specify a time of day when rescheduling.
- Remove "Overmorgen" option 
- - > One option to work around this could be to ask the user when they are available most of the time upon onboarding. Then the VC can start an activity dialog at the preferred time. 
- The rescheduling dialog should be preceded by a short introduction of the activity (purpose/name/duration). 
- It would be useful to define essential activities which the user cannot reschedule. 
- If an essential activity gets started, mention why the activity is mandatory. Essential activities could be marked with a specific symbol which is introduced at the beginning of the PF intervention. 
- Optional activity could be skipped altogether. 
- For optional activities, think about a build-in option for the user to select 'I don't want to do this activity' (after x times of having asked to reschedule?). Maybe this can be solved with the drop-down menu of activities. 
- We agreed to make an overview of dialogs to be created to have an estimation of how many need to be developed in total. Based on that, we can divide the dialogs based on expertise (expert takes the lead on that dialog). 
- We could ask Anke and Veronica to take a look at the dialogs first and check if the language level is appropriate for the target group. Pharos and Stiching ABC could potentially also be asked to help with this.
