### ISSUE TITLE
Action points after sprint closing

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/content-development#23]
- [x] @KristellP write email to Anke about dialog overview
- [x] @Milonvv decide on real final date for virtual coach
- [x] @KristellP & @Milonvv talk to Anke, Eline, Veronica, Winnie making time content development how to approach it?
- [x] @KristellP & @Milonvv write a draft content development planning, @svenvanderburg will check it. (@svenvanderburg will resend a link to software development planning)
- [x] @KristellP run future self activity by Veronica & Winnie
- [x] @svenvanderburg will make sure to implement dialog 1 in the virtual coach

In software development planning should go:
- [x] When is a dialog done? When final dialog. I.e. definition of done
- [x] What are true must have dialogs?
- [x] Who does what and in which form?

**Comment by Milonvv** [comment]
Extra notes for planning: Make milestones (general issues that need to be solved; must-have dialogs etc.) and link issues. Plan an new sprint?

**Comment by svenvanderburg** [comment]
Here is [the link](https://leidenuniv1.sharepoint.com/:w:/r/sites/AcademischePartnersPerfectFit/Shared%20Documents/General/NLeSC%20-%20RFCs/PerfectFit-RFC-0007-software-development-planning.docx?d=w6526726e65054e5fbb0b6e1240bb5952&csf=1&web=1&e=8zTndC) to the software development planning document.
