### ISSUE TITLE
Define trajectory for PA (re)lapse 

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#26]
Lapse for PA is integrated in weekly reflection. 

- [x] Define relapse for PA including thresholds based on answers from questionnaire to advisory board
- [x] Discuss with Anke and Eline
- [x] Decide whether we explain the difference between lapse and relapse in a dialog or separate resource

**Comment by Milonvv** [comment]
Different behaviors to set goals for, and to (re)lapse:
1) smoking - lapse: smoked one cigarette & relapse: back to baseline level (smoking again)
2) PA: running or walking, measured via steps - ...
3) PA: other sports, need to keep track of it themselves - ...

**Comment by Milonvv** [comment]
- bij user-initiated wel PA HRS, maar PA (re)lapse gewoon in de weekly reflection
- Bij weekly reflection: Tips om te motiveren - bijstellen doel
- Andere sport doen: Ga je dan alsnog feedback geven op stappen? - Ga je dan alsnog aansturen op 4000 stappen per dag? Of geef je alleen feedback op de sportdoelen? --> Alleen feedback op sportdoelen in weekly reflection, maar wel positieve feedback / notificatie wanneer ze actief zijn (boven 4000 per dag).
- Misschien 4000 stappen per dag wel als voorbeeld geven bij doelen stellen of PA richtlijnen resource verplicht maken

**Comment by Milonvv** [comment]
PA: geen onderscheid tussen relapse / lapse
- Voor sport wat niet met stappen gemeten wordt: alleen dialoog op lapse in weekly reflection verwerken
- Running of wandelen: in weekly reflection evalueren hoe het gegaan is, zelf laten evalueren, legt het neer bij de gebruiker (ook terugkomen op lapse wanneer dit gebeurt is); wel positieve feedback met notificaties elke dag wanneer stappendoel gehaald
--> wel feedback wanneer onder minimum stappen doel (lapse gedetecteerd) - los van de weekly reflection, gewoon direct.
