### ISSUE TITLE
Operationalize First-Aid Kit (FAiK)

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#27]
- [x] Decide on base app
- [x] Overview of FAiK content in the app
- [x] Think about how users can alter FAiK 
- [x] Write title (+ korte subtitle wanneer nodig), description (same resource text or adjusted version if participants answers matter, e.g., barriers for smoking and PA) for each activity in the FAiK
- [x] Decide for which activities the users get to see full instructions rather than only the title and short description
- [x] Decide how many activities to show in the FAiK

**Comment by Milonvv** [comment]
- short title + some description when needed (bijv. als de korte titel niet meteen een hele duidelijke samenvatting is van de oefening)
- Optie om toe te voegen bij general activity dialog (standaard activity)
- User eigen tekst laten schrijven soms (bijv. bij alternative behaviors)
- Wanneer ze first aid kit typen, krijgen ze een lijst met titels, en dan kunnen ze aangeven dat ze bepaalde titels kunnen noemen waarvan ze de description willen zien
- [x] Bij FAiK, voor activiteiten waarbij eigen input is gegeven, dan een algemene omschrijving laten zien en als zij erop klikken dan een uitgebreidere omschrijving/vragen of zij hun eigen input willen aanpassen?

**Comment by Milonvv** [comment]
- 5 activiteiten in EHBO doos
- Rating geven van hoe nuttig (smileys) - op basis daarvan de 5 meest relevante in EHBO-doos; de minder relevante verdwijnen eruit. Als ze dan overal dezelfde rating geven kunnen we random een paar uitkiezen
