### ISSUE TITLE
Create list of commands

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#28]
Define a list of commands which can be used by the user to initiate an interaction with the VC

**Comment by KristellP** [comment]
Suggestions for commands: 
- Help (in HRS / (re)lapse, launch dialog C1.19)
- EHBO (to see their FAiK, launch dialog C1.21)
- Oefening (to do an activity, launch dialog C1.16 [General Activity Dialog])
- Plan (send a message summarizing their weekly plan created during the reflection dialog)
- Voorkeuren [NOG EEN MAKKELIJKER WOORD VOOR BEDENKEN] (send a message to be able to change settings (e.g., message frequency, preferred contact moment))
- Medicatie (in case they want to do want to use medication later on, launch dialog C1.6)
- Progressie [NOG EEN MAKKELIJKER WOORD VOOR BEDENKEN - Groei? Score? Activiteit?] (to view their (step/intensiry) progress, launch bar charts and graphs)

- All commands should not be caps sensitive

**Comment by Milonvv** [comment]
- See progress visualization

**Comment by Milonvv** [comment]
- [x] List of key words
- [x] What to do with typos? Welke typos kunnen gemaakt worden?
