### ISSUE TITLE
Determine frequency of messages

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#35]
- [x] Cynthia, Milon and Kristell make a proposal 
- [x] Kristell discusses with Nele
- [x] Discuss with Anke and Eline

**Comment by Milonvv** [comment]
- Preparation phase: Wel goed om op de stopdag sowieso iets te laten weten
- Aanpassen op de gebruiker - dus intensiever en minder intensief + schedulen 
- Wat als de gebruiker helemaal niets doet? - Mogelijk een dialoog voor als iemand helemaal niets doet, push notificaties of een dialoog om iemand dan te motiveren --> Nele ook mee bezig? Vragen?
- Ochtenden zijn vaak moeilijk en vooral eerste dagen na stopdag of op de dag dat ze gepland hebben om te bewegen - dan motiverende berichten sturen + evt. ook dan doorverwijzen in dat berichtje naar de coach, "typ dit als je dit wilt doen"
- Belangrijk om mensen te instrueren dat ze pushnotificaties moeten toestaan (bij app installeren) - voor RCT

**Comment by Milonvv** [comment]
- [x] Meer of minder notificaties (intensive vs. mild program) instelling bij voorkeuren aan het begin en notificaties tijdens interventie hierop aanpassen?
- [x] Mogelijk een dialoog voor als iemand helemaal niets doet, push notificaties of een dialoog om iemand dan te motiveren --> Nele ook mee bezig? Vragen?
