### ISSUE TITLE
Visualization of progress towards goals

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#37]
- [x] In general, determine how to visualize progress
- [x] Decide on what aspects to visualize (money saved, lung capacity, progress towards goals)

**Comment by KristellP** [comment]
- [ ] Nice visualizations: View streaks (days smoke free, days step/PA goal has been reached), countdown to quit date, days spent on the program, number of PAs
- [ ] Show on request (from one of the commands). In weekly dialog, offer to show the progress.
- [ ] Wat doen we als het nog de eerste week is? Hoe gaan we dit visualiseren? Op basis waarvan laten we progress zien (bijv. streaks cigarettes, money saved, health)?

**Comment by Milonvv** [comment]
- Ask for progress by using certain keyword
- Ask if they want to see their progress during goalsetting / weekly reflection dialog for instance,
- Wat doen we als het nog de eerste week is? Hoe gaan we dit visualiseren? Op basis waarvan laten we progress zien (bijv. streaks cigarettes, money saved, health)?

**Comment by Milonvv** [comment]
Anke / Eline / Kariene:
- Niets doen aan feedback wat je niet kunt meten (geen 'gezondheidsfeedback' bijv).
- notificaties bij mijlpalen (bijv. 6 weken bezig, niet te gepersonaliseerd) - evt doorlinken naar reward resource
- Iets meer rewards / mijlpalen in eerste week 
- Weekly reflection ook feedback teruggeven 
- Easiest way to track progress is to say something like 'Congrats, you are starting week x of the program'.

**Comment by KristellP** [comment]
- [ ] Easiest way to track progress is to say something like 'Congrats, you are starting week x of the program'.

**Comment by Milonvv** [comment]
- [ ] Read paper suggested by Nele which relates to this topic: Rutjes, H., Willemsen, M. C., Feijt, M. A., & IJsselsteijn, W. A. (2022). The Influence of Personal Health Data on the Health Coaching Process. Frontiers in big Data, 5.

**Comment by KristellP** [comment]
Tijdens laatste overleg besproken dat wij nu aan het begin van elke week een notificatie sturen om de gebruiker te informeren dat zij in week x zitten. Geen verdere progress visualization omdat wij daar geen tijd meer voor hebben en het geen must-have must-have is.
