### ISSUE TITLE
Discuss preferred app settings

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#38]
One Kristell has completed her interviews with experts and knows which coaching techniques are preferred, Kristell and Nele will have a chat about preferred coaching settings (frequency, tone, number of different coaches, possibility to change settings on demand)

**Comment by Milonvv** [comment]
- [x] Nele will send a list of the variables that need to be asked about + the questionnaire that can be used for that
- [x] Kristell will provide the Dutch version of identity questionnaire
