### ISSUE TITLE
Bespreken of elke PF deelnemer stappendoelen krijgt, of dat iemand bijv. ook alleen op een andere soort sport kan focussen

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/content-development#40]

**Comment by KristellP** [comment]
User category 1: only step goal, limited coaching (we don't plan walks and do not follow-up on after each walk, we simply keep track of their steps and how far away they are. We can give tips for achieving their step goal)
User category 2: step + PA goal, full coaching (we do plan the runs and follow-up on how it went)
User category 3: other PA than walking or running (we do plan and follow-up on how it went)

**Comment by Milonvv** [comment]
- detailed coaching running and walking
- Can do other kind of sports / PA, for which they will receive the general coaching (motiveren, making a PA plan, weekly reflection)
- In de goalsetting dialoog komen wel vragen om een doel SMART te maken
- En we kunnen ze ook de WHO guidelines duidelijk maken over wat het advies is + advies wat Bouke weet
- Kunnen evt. ook (motiveren om te) vergelijken of ze het WHO doel gehaald hebben die week (in de weekly reflection)
- SMART goals and implementation intentions zijn belangrijk, dan kunnen ze er als het goed is mee aan de slag

**Comment by Milonvv** [comment]
Nieuw plan: We laten gebruikers eigenlijk alleen doelen stellen en coachen alleen op stappen (kwantiteit) en op hartslag (intensiteit). De overige takken (overige sport en combinatie) komen te vervallen.

Bij doelen op basis van stappen zijn er twee 'categorieen':

1) Begin categorie, waarbij iemand inactief is (onvoldoende stappen) en stappen moet gaan verhogen: Stappendoel die elke dag aangepast wordt op o.b.v. stappen van 9 dagen ervoor (pakt de 7e hoogste dag van de 9 als doel). Langzaam opbouwen. Als mensen dus minder stappen zetten, dan vermindert het doel dus ook.
2) Wanneer iemand al een bepaald basisniveau (voldoende) heeft, ook intensiteit gaan verhogen: Niet alleen meer stappen zetten, maar ook intensiever sporten (hartslag, via horloge). Dit kan in de vorm van actiever wandelen (bijv. nordic walking) of hardlopen, maar zou bijv. ook fietsen kunnen zijn. Bijv. gestructureerd programma met 2-3x per week hardlopen

Grootste groep zal in categorie 1 zitten. Doel is om ze naar groep 2 te krijgen in 6 weken tijd.

Baseline bepalen voor stappen duurt dus min. 9 dagen (tracking dailoog in voorbereidingsfase), dus goal-setting dialoog zou dan na 9 dagen opgestart moeten worden

PA doel is dus volledig system-initiated en doen we dus niet user-initiated. 

- [x] In introtekst van goal-setting dialoog ook noemen dat we met het PF programma alleen focussen op een bepaald aantal stappen per dag, om zo te zorgen dat iemand regelmatig en elke dag beweegt (zitgedrag verminderen), maar dat dit niet betekent dat iemand niet ook andere sporten kan ondernemen om actief te zijn. Noemen dat het juist heel goed is om ook andere sporten te doen en dat sommige sporten ook zorgen dat je stappen aantal verhoogt, dus alsnog kan helpen om je stappen aantal ook te verhogen.
