### ISSUE TITLE
Translate Goal-setting dialog from Beyza

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#42]
- [x] Translate the dialog itself
- [x] #97

**Comment by Milonvv** [comment]
https://github.com/PerfectFit-project/goal_setting_virtual_coach/blob/main/experiment_data/goals.csv

**Comment by Milonvv** [comment]
Goal-setting dialog: 
- Which testimonial is shown is determined by the algorithm from Nele - so this should be implemented in the dialog
- Although the step goal per day is system-initiated, we still want the user to think about the higher-order goal / motivation to become more physically active / increase steps. This part of the dialog from Beyza needs to be integrated in the Goal-setting dialog.
- The only time that users will be asked to reflect on the higher-order goal, will be during the closing dialog - integrate this in the dialog
