### ISSUE TITLE
Koppelen HRS/lapse/relapse reasons aan activiteit (beleid) 

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#44]
- [ ] Lijstje opstellen
- [ ] Bespreken hoe te verwijzen in geval van relapse

**Comment by Milonvv** [comment]
- Voorleggen dat het kan helpen om naar een huisarts, stoplijn bellen of iets anders toe gaan - motiveren ook dat dat normaal is en helpen hoe ze het kunnen aanvliegen
- 2e keer stoplijn + activiteiten; 3e keer huisarts + activiteiten

**Comment by KristellP** [comment]
- Nele is working on: algorithm to choose a message to persuade them to complete an activity. Nele will also write messages for this. 

+ Working on predicting which activities would be useful to do when. 

Conclusion: ok to randomly pick activities, as long as we are transparent.

**Comment by Milonvv** [comment]
Voor momenten in de interventie waarop de coach de user laat kiezen uit een lijstje van verschillende activiteiten:
--> Nele heeft clusters gemaakt (studie over competenties, afgenomen bij rokers), dus we kunnen ze de keuze geven om te kiezen tussen deze cluster namen (bijv. ik wil een praktische activiteit doen of een activiteit om mijn motivatie te verhogen)en dan vervolgens als ze 1 cluster/onderwerp kiezen geven we ze de lijst met activiteiten die bij dit cluster horen of we geven ze een selectie van 3 activiteiten die bij dit cluster horen (wat wij willen)
--> Nele zal deze clusters delen

Verwerk dit in de HRS/(re)lapse dialoog
