### ISSUE TITLE
Hoe zorgen we dat 'general activities' die niet optioneel zijn en op een vast moment voltooid moeten worden op het goede moment geactiveerd worden?

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/content-development#48]
Bijv. General activities zoals ontspanningsoefeningen kunnen op elk moment gedaan worden door user tijdens interventies. Maar general activities zoals future self exercise, alternative behaviors en education about physical transformations willen we de user op een specifiek moment in de interventie laten doen.

**Comment by KristellP** [comment]
Dit kan obv aantal dagen bezig met de interventie. Maar het kan ook worden gestart op de dag die gepland is tijdens de weekly reflection.

**Comment by Milonvv** [comment]
- Task scheduler is al gemaakt: Hiermee kunnen activiteiten gepland worden, dus bijv. na een bepaalde activiteit compleet is of op een specifieke dag / tijd
