### ISSUE TITLE
Gaan we nog advies geven voor blessure risico's en preventie? (MOSCOW should-have)

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/content-development#50]

**Comment by KristellP** [comment]
Wel nog een stukje over voorkomen dat zij te veel in één keer gaan doen.

**Comment by Milonvv** [comment]
Toevoegen in de goalsetting dialoog (introductie van deze dialoog) - Bouke gaat een lijst opstellen met een paar punten die we dan echt moeten noemen. Zoals bijv. dat mensen rustig moeten opbouwen. 

- [x] Bouke stuurt dit voor het einde van de week naar Milon op.

**Comment by Milonvv** [comment]
Tekst Bouke: "Wanneer je meer gaat bewegen is het belangrijkom dit langzaam uit te bouwen. Het stappendoel zal zo worden gemaakt dat dit een voor jou haalbaar doel is. Dit doel bouwt langzaam op. Als je een keer meer wilt doen is dat geen probleem. Let er wel op dat je niet te veel, te snel doet. Dit kan leiden tot blessures. Het is beter om iedere dag ietsje meer te doen dan plotseling heel veel."
