### ISSUE TITLE
Telt PF als steun bij SMR voor NVM voor zorgverzekeraars?

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#56]

**Comment by Milonvv** [comment]
Eline: Ik denk niet dat PF telt als gedragsmatige ondersteuning voor de zorgverzekeraar, omdat het nog niet evidence based is. Dus dan wordt medicatie alleen vergoed als mensen een ander traject hebben lopen bijvoorbeeld via de huisarts of een andere aanbieder die wordt vergoed (sinefuma oid)

**Comment by Milonvv** [comment]
Kristell: Dankjewel voor de snelle reactie. Ik geef het door aan Kariene en wij passen het medicatiedialoog daarop aan. Ons idee is om gebruikers minder stellig proberen te motiveren medicatie te gebruiken omdat zij er zelf voor moeten betalen, en eerder aansturen op het gebruik van NVM zoals pleisters, kauwgom etc. Zijn jullie het daarmee eens?

**Comment by Milonvv** [comment]
Anke/Eline: Dat lijkt me een goed idee. Denk wel dat het goed is als ze wel alle informatie hebben over de (ondersteunings)mogelijkheden, maar daar mag je wel eerlijk in zijn qua kosten. 

Ja, is ook in lijn met de richtlijn want NVM zijn eerste keuze (die hebben nl minder bijwerkingen dan medicatie op recept). Voor andere medicatie zou ik ze vooral aanmoedigen om naar de huisarts te gaan, als ze dan bijvoorbeeld de POH een paar keer zien wordt de medicatie ook vergoed aangezien ze dan wel gedragsmatige ondersteuning hebben die telt voor de zorgverzekeraar.
