### ISSUE TITLE
Beleid bij relapse uitdenken 

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#58]

**Comment by Milonvv** [comment]
Kristell sent email to Anke, Eline and Kariene

**Comment by Milonvv** [comment]
Anke: 
Wat bedoel je precies met ‘verwijzen wij ze gelijk naar de Stoplijn of de huisarts’? M.i. kun je ze – in de app – advies geven over de alternatieve (zoals de stoplijn en de huisarts), maar dat gebeurt nu toch al bij de relapse? Wat zou je dan nog meer willen doen? We kunnen – op basis van de gegevens in de app – geen (andere) zorg aanbieden, want dan zouden we als medisch hulpmiddel worden gezien (want dan maakt de app keuzes wie wel of geen extra hulp krijgt). 
 
Ik denk dat het aan de persoon zelf is om wel of niet gebruik te maken van de extra middelen die er beschikbaar zijn (en waar naar verwezen wordt). Denk persoonlijk dat men altijd gebruik moet kunnen maken van Perfect Fit, ook al heeft hij/zij meer dan 3 relapsen gehad. Het niet aanbieden, zo ook onethisch zijn. 
 
Of bedoelde je het anders?

**Comment by Milonvv** [comment]
Milon:
Ohja, ik had even niet gedacht aan de MDR. Dat betekent dus dat we wel advies kunnen geven om de stoplijn of huisarts te contacten bij een relapse (wat we inderdaad doen), maar niet meer dan dit kunnen doen dus?

Ik denk dat voor mij de grootste vraag is hoe we dan een soort eindpunt bepalen, van wanneer het niet meer ethisch / haalbaar is om iemand te helpen met de Perfect Fit app. Dus iemand doet bijv. mee aan het onderzoek, is net bezig met de uitvoeringsfase en komt dan in een smoking relapse in week 3. Diegene doorloopt relapse dialoog en krijgt de daarin verwerkte adviezen etc. Vervolgens pakt diegene de draad weer op en telt de uitvoeringsfase weer verder vanaf week 3. Vervolgens gebeurt dit ook in week4, en in week 5 etc. Dus eigenlijk biedt de Perfect Fit app dan bijv. niet genoeg ondersteuning voor deze persoon… Wat doen we dan als iemand het wel blijft proberen? Komt iemand dan alsnog uiteindelijk via x aantal relapsen bij de afsluitende fase? Of moeten we op een bepaalde manier bepalen dat we dan niet genoeg ondersteuning kunnen bieden? Of ga je er vanuit dat deze mensen vanzelf een ‘dropout’ zullen worden?

Wat denken jullie hierover?

**Comment by Milonvv** [comment]
Eline:
Goeie vraag, eens met Anke. Ik zou zeggen dat we mensen moeten blijven ondersteunen en tegelijk wijzen op opties als huisarts en stoplijn, dus ook als ze elke week 3x blijven roken. Dat kunnen we niet op een meer gepersonaliseerde manier, of proactiever, gaan doen dan we nu al doen omdat je dan inderdaad te dicht bij een medical device komt. Hierin is het dus ook belangrijk dat we in de onboarding goed uitleggen wat de app wel en niet doet. Het moet dus duidelijk zijn dat het ook de eigen verantwoordelijkheid van de gebruiker blijft wat ze doen.
Daarbij is stoppen met roken een proces dat vaak met hobbels gaat, en proberen de meeste Nederlandse rokers het gewoon op eigen houtje, dus als wij ze ook als ze 20x relapsen wel betrouwbare ondersteuning kunnen bieden (al is het niet toereikend) is dat al beter dan niks / gewoon door blijven roken. Voor de trial moeten we goed kijken wie we excluderen (bijv zwanger, mensen die antipsychotica gebruiken), en als de intervente later algemeen beschikbaar zou komen moet dat ook goed afgebakend worden. Of (na de trial) als mensen uit risicogroepen wel mee willen doen, dat ze dan zelf bevestigen dat ze ook ondersteuning hebben van een huisarts/verslavingsarts/wat dan ook en pas dan verder kunnen met de app.

**Comment by Milonvv** [comment]
Kristell: 

Dit helpt zeker, dank voor jullie reactie Eline en Anke. De conclusie is volgens mij dat wij de ondersteuning op dit moment zo goed mogelijk doen en het beste zo kunnen laten om er geen medical device van te maken. En dat we bij relapse de weken blijven doortellen. Relapsers beginnen niet opnieuw met 12 weken interventie.  

Daarnaast belangrijk om  in de analyse fase van de trial uiteindelijk de relapses en succesrate in kaart te brengen.
