### ISSUE TITLE
Maak een lijst van woorden die de chatbot moet herkennen omdat er actie moet worden ondernomen

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#60]

**Comment by Milonvv** [comment]
- De lijst met woorden is niet nodig - wanneer je dit doet ga je ook juist signaleren als het slecht gaat, maar kan je hier niet voldoende ondersteuning voor bieden vervolgens, wat niet helemaal volgens de medical device richtlijnen is.
- In de introductievideo geven we wel al aan dat de chatbot een robot is en geen echt mens

- [x] Vragen aan technische team of er wel al duidelijk gemaakt wordt door chatbot in dialogen dat wanneer iemand met iets anders antwoord dan bijv. 1, 2 of 3, dat de chatbot hier niet op kan antwoorden en het antwoord niet snapt (dan geef je namelijk ook automatisch de beperkingen / grenzen van de chatbot aan) Answer: We double checked this with the technical team, they will build the limitations in functionalities and Milon will mention that the coach is a robot during onboarding.
