### ISSUE TITLE
Create overview of which (coping) activity to implement when and how to persuade people to do these activities.

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#66]

**Comment by Milonvv** [comment]
Voor momenten in de interventie waarop de coach de user laat kiezen uit een lijstje van verschillende activiteiten:
 --> Nele heeft clusters gemaakt (studie over competenties, afgenomen bij rokers), dus we kunnen ze de keuze geven om te kiezen tussen deze cluster namen (bijv. ik wil een praktische activiteit doen of een activiteit om mijn motivatie te verhogen)en dan vervolgens als ze 1 cluster/onderwerp kiezen geven we ze de lijst met activiteiten die bij dit cluster horen of we geven ze een selectie van 3 activiteiten die bij dit cluster horen (wat wij willen) 
--> Nele zal deze clusters delen

- [x] Activiteiten onderverdelen in de clusters
- [x] Verwerk dit in de HRS/(re)lapse dialog
- [x] Verwerk dit in de General Activity dialog
