### ISSUE TITLE
Denk na over naam en zoek plaatje voor coach

### ISSUE THREAD

**Issue by Tessdv** [PerfectFit-project/content-development#69]

**Comment by KristellP** [comment]
Personalisatie coach: 
- [x] Plaatje van robot of gender neutral poppetje
- [x] Naam coach
The advisory board did not find very important to personalize more.

**Comment by Milonvv** [comment]
Technical: It is possible to create a therapist account with an avatar and name. However, this will be the same for everyone: 
- [x] Decide on a genderneutral name
- [x] Decide on some kind of image
