### ISSUE TITLE
Notifications: how? what? when?

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#70]
- [x] Ask the technical team whether it is possible to send the user notifications or it that is hard to implement.
- [ ] @nelealbers - two options: they plan to complete activities during the weekly reflection/planning dialog or we send them notifications throughout the week and persuade them to complete activities (can use command 'activiteit'). Which is in line with what you are working on and is technically easier to implement?
- [ ] Let user define frequency of messages during profile creation: is this an option?

**Comment by Milonvv** [comment]
Technical: General text messages popup, can be implemented / easy to implement

**Comment by KristellP** [comment]
Closing issues because we have discussed with Walter and Bouke that we have to critically look at which notifications will be sent when.
