### ISSUE TITLE
Schedule of user - planning activities according to schedule

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#72]
- [x] Ask the technical team what is easier when it comes to learning when the user is available? Advisory board prefers indicating this during the profile creation and be able to alter this if their week changes. 
- [x] Doable to register this during profile creation? 
- [x] Doable to let the user alter this during the weekly reflection or by going back to that section of the profile creation. 
--> NICE TO HAVE

**Comment by Milonvv** [comment]
Technical team: It is both possible as the scheduler already works. We can decide as content team what we want.

- [x] Implement content to make sure that we know the schedule of the user and plan the activities according to this
