### ISSUE TITLE
Implement emoji's in intervention

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/content-development#74]
Important to incorporate this seen our focus on lower SEP. How much work is it to implement if we send you the emoji's to be used?

Ask technical team about incorporating emoji's in:
- [x] Resources 
- [x] Notifications
- [x] Dialogs

**Comment by KristellP** [comment]
Answer: the technical team is unable to assess the amount of work this would take. They will explore this and also let us know how they want us to provide the emoji's. Op de agenda voor 22 november.

**Comment by Milonvv** [comment]
We can implement emoji's from this website: https://emojipedia.org/
